// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "KotlinToSwift",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "KotlinToSwift",
            targets: ["AppModule"],
            bundleIdentifier: "com.evernetica.kotlin-to-swift.KotlinToSwift",
            teamIdentifier: "G294247VY6",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .carrot),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/Alamofire/Alamofire", "5.8.1"..<"6.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Alamofire", package: "alamofire")
            ],
            path: "."
        )
    ]
)